### ISSUE TITLE
Questions about compiling the benchmark

### ISSUE THREAD

**Issue by jinz2014** [omp2ocl/Unibench#2]
I got the following message using the command ./unibench compile all.  Thanks for fixing the missing files and memory double free!

Compiling mri-q
Makefile:10: benchmarks/Polybench/2MM/src/Makefile: No such file or directory
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile -lm -ffast-math ./benchmarks/Parboil/mri-q/../common/parboil.c ./benchmarks/Parboil/mri-q/src/mri-q.c -o ./benchmarks/Parboil/mri-q/build/mri-q
Compiling sgemm
make: *** No rule to make target 'benchmarks/Polybench/2MM/src/Makefile'.  Stop.
clang++ -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile  ./benchmarks/Parboil/sgemm/../common/parboil.c ./benchmarks/Parboil/sgemm/src/sgemm.cpp -o ./benchmarks/Parboil/sgemm/build/sgemm
Compiling spmv
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile  ./benchmarks/Parboil/spmv/../common/parboil.c ./benchmarks/Parboil/spmv/src/convert_dataset.c ./benchmarks/Parboil/spmv/src/mmio.c ./benchmarks/Parboil/spmv/src/spmv.c -o ./benchmarks/Parboil/spmv/build/spmv
Compiling 2DCONV
Compiling stencil
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/2DCONV/src/2DConvolution.c -o ./benchmarks/Polybench/2DCONV/build/2DCONV
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile  ./benchmarks/Parboil/stencil/../common/parboil.c ./benchmarks/Parboil/stencil/src/stencil.c -o ./benchmarks/Parboil/stencil/build/stencil
Compiling 3DCONV
Makefile:10: benchmarks/Polybench/CORR/src/Makefile: No such file or directory
make: *** No rule to make target 'benchmarks/Polybench/CORR/src/Makefile'.  Stop.
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/3DCONV/src/3DConvolution.c -o ./benchmarks/Polybench/3DCONV/build/3DCONV
Compiling 3MM
Compiling ATAX
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/3MM/src/3mm.c -o ./benchmarks/Polybench/3MM/build/3MM
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/ATAX/src/atax.c -o ./benchmarks/Polybench/ATAX/build/ATAX
Compiling BICG
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/BICG/src/bicg.c -o ./benchmarks/Polybench/BICG/build/BICG
Compiling COVAR
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/COVAR/src/covariance.c -o ./benchmarks/Polybench/COVAR/build/COVAR
Compiling FDTD-2D
Compiling GEMM
Compiling GESUMMV
Compiling MVT
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/GEMM/src/gemm.c -o ./benchmarks/Polybench/GEMM/build/GEMM
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/FDTD-2D/src/fdtd2d.c -o ./benchmarks/Polybench/FDTD-2D/build/FDTD-2D
Compiling SYR2K
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/MVT/src/mvt.c -o ./benchmarks/Polybench/MVT/build/MVT
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/GESUMMV/src/gesummv.c -o ./benchmarks/Polybench/GESUMMV/build/GESUMMV
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/SYR2K/src/syr2k.c -o ./benchmarks/Polybench/SYR2K/build/SYR2K
Compiling SYRK
clang -O3 -fopenmp -omptargets=opencl-unknown-unknown -opt-poly=tile   ./benchmarks/Polybench/SYRK/src/syrk.c -o ./benchmarks/Polybench/SYRK/build/SYRK
mv: cannot stat 'kernel*': No such file or directory

mv: cannot stat 'kernel*': No such file or directory

mv: cannot stat 'kernel*': No such file or directory

mv: cannot stat 'kernel*': No such file or directory

mv: cannot stat 'kernel*': No such file or directory

mv: cannot stat 'kernel*': No such file or directory

mv: cannot stat 'kernel*': No such file or directory

** Error in `ppcg': double free or corruption (!prev): 0x0000000000a5a8e0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f7c80a747e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f7c80a7d37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f7c80a8153c]
/lib/x86_64-linux-gnu/libc.so.6(fclose+0x103)[0x7f7c80a6a363]
ppcg[0x41443d]
ppcg[0x4107de]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f7c80a1d830]
ppcg[0x410859]
======= Memory map: ========

**Comment by iviarcio** [comment]
Missing Makefile for 2mm and correlation. Fixed.
